### ISSUE TITLE
java.lang.IllegalArgumentException: itemCount <= 0

### ISSUE THREAD

**Issue by ghost** [sockeqwe/AdapterCommands#1]
When I set the adapter's items to an empty List twice in a row,
I get the above error at at `com.hannesdorfmann.adaptercommands.command.ItemRangeRemovedCommand.<init>(ItemRangeRemovedCommand.java:40).`

This is how I initialise my adapter:

```
        adapter = new SchoolAdapter(this);
        recyclerView.setAdapter(adapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        commandsCalculator = new DiffCommandsCalculator<>(true, SchoolItem.ITEM_CHANGE_DETECTOR);
        commandProcessor = new AdapterCommandProcessor(adapter);
```

This is how I clear out my adapter:

```
        List<SchoolItem> schools = Collections.emptyList();
        adapter.setItems(schools);
        commandProcessor.execute(commandsCalculator.diff(schools));

```

**Comment by sockeqwe** [comment]
Thanks for reporting.
I have released `1.0.3` (may take some hour until distributed) containing this fix.
