### ISSUE TITLE
Support for Object Payloads

### ISSUE THREAD

**Issue by FabianShallari** [sockeqwe/AdapterCommands#3]
Hi Hannes.

Recent versions of the support library include support for sending optional object payloads in the various notification methods of the `RecyclerView.Adapter`: 

```
void notifyItemChanged (int position, 
                Object payload)

void notifyItemRangeChanged (int positionStart, 
                int itemCount, 
                Object payload)

etc...
```

These methods are extremely useful in determining the right animations when writing your own `RecyclerView.ItemAnimator` , for example by recording custom `ItemInfo` when `recordPreLayoutInformation(..)` is called and passing the right info to the various animation methods of the `RecyclerView.ItemAnimator`.

This is potentially a very big change therefore I am enquiring if this is out of the scope of the current release and/or is doable at all. 

Would be happy do contribute with a pull request if so.

**Comment by sockeqwe** [comment]
Hi there, 
to be honest I was thinking about deprecating this library because latest support library has introduced a class called `DiffUtils` which basically does the same and implements the same algorithm.

**Comment by FabianShallari** [comment]
I see. 

Well closing this since it is no longer your plan to maintain it.

Cheers
